-- Filtro de lenguaje inapropiado (multi-idioma) + salida real del chat.
--
-- 1) Salir del chat lo borra de verdad (RPC leave_chat, cascada limpia
--    mensajes y participantes) — antes "Salir" solo cerraba la vista local.
-- 2) Moderación de mensajes: trigger BEFORE INSERT censura palabras de una
--    lista de ~2.560 términos en 26 idiomas (dataset público LDNOOBW) y
--    lleva la cuenta de advertencias por (sala, usuario). Al 3er mensaje con
--    lenguaje inapropiado, la sala se borra sola (cancela ese insert, cierra
--    para las dos familias). No es 100% infalible (matching por substring,
--    sin lookahead complejo) — es un filtro razonable, no un sistema perfecto.

create extension if not exists unaccent with schema extensions;

create table if not exists banned_words (
  word text primary key,
  lang text not null
);

create table if not exists chat_warnings (
  chat_id uuid references chats(id) on delete cascade,
  user_id uuid not null,
  count int not null default 0,
  primary key (chat_id, user_id)
);

alter table banned_words enable row level security;
alter table chat_warnings enable row level security;
-- Sin policies en ninguna de las dos: nadie las lee/escribe directo desde el
-- cliente, solo las tocan las funciones SECURITY DEFINER de abajo.

insert into banned_words (word, lang) values
('سكس', 'ar'),
('طيز', 'ar'),
('شرج', 'ar'),
('لعق', 'ar'),
('لحس', 'ar'),
('مص', 'ar'),
('تمص', 'ar'),
('بيضان', 'ar'),
('ثدي', 'ar'),
('بز', 'ar'),
('بزاز', 'ar'),
('حلمة', 'ar'),
('مفلقسة', 'ar'),
('بظر', 'ar'),
('كس', 'ar'),
('فرج', 'ar'),
('شهوة', 'ar'),
('شاذ', 'ar'),
('مبادل', 'ar'),
('عاهرة', 'ar'),
('جماع', 'ar'),
('قضيب', 'ar'),
('زب', 'ar'),
('لوطي', 'ar'),
('لواط', 'ar'),
('سحاق', 'ar'),
('سحاقية', 'ar'),
('اغتصاب', 'ar'),
('خنثي', 'ar'),
('احتلام', 'ar'),
('نيك', 'ar'),
('متناك', 'ar'),
('متناكة', 'ar'),
('شرموطة', 'ar'),
('عرص', 'ar'),
('خول', 'ar'),
('قحبة', 'ar'),
('لبوة', 'ar'),
('bordel', 'cs'),
('buzna', 'cs'),
('cumet', 'cs'),
('curak', 'cs'),
('debil', 'cs'),
('do pice', 'cs'),
('do prdele', 'cs'),
('drstka', 'cs'),
('drzka', 'cs'),
('flundra', 'cs'),
('hajzl', 'cs'),
('hovno', 'cs'),
('chcanky', 'cs'),
('chuj', 'cs'),
('jebat', 'cs'),
('kokot', 'cs'),
('kokotina', 'cs'),
('konomrd', 'cs'),
('kunda', 'cs'),
('kurva', 'cs'),
('mamrd', 'cs'),
('mrdat', 'cs'),
('mrdka', 'cs'),
('mrdnik', 'cs'),
('oslosoust', 'cs'),
('pica', 'cs'),
('picus', 'cs'),
('pichat', 'cs'),
('pizda', 'cs'),
('prcat', 'cs'),
('prdel', 'cs'),
('prdelka', 'cs'),
('sracka', 'cs'),
('srat', 'cs'),
('soustat', 'cs'),
('sulin', 'cs'),
('vypicenec', 'cs'),
('zkurvit', 'cs'),
('zkurvysyn', 'cs'),
('zmrd', 'cs'),
('zrat', 'cs'),
('anus', 'da'),
('bøsserøv', 'da'),
('cock', 'da'),
('fisse', 'da'),
('fissehar', 'da'),
('fuck', 'da'),
('hestepik', 'da'),
('kussekryller', 'da'),
('lort', 'da'),
('luder', 'da'),
('pik', 'da'),
('pikhar', 'da'),
('pikslugeri', 'da'),
('piksutteri', 'da'),
('pis', 'da'),
('røv', 'da'),
('røvhul', 'da'),
('røvskæg', 'da'),
('røvspræke', 'da'),
('shit', 'da'),
('analritter', 'de'),
('arsch', 'de'),
('arschficker', 'de'),
('arschlecker', 'de'),
('arschloch', 'de'),
('bimbo', 'de'),
('bratze', 'de'),
('bumsen', 'de'),
('bonze', 'de'),
('dodel', 'de'),
('fick', 'de'),
('ficken', 'de'),
('flittchen', 'de'),
('fotze', 'de'),
('fratze', 'de'),
('hackfresse', 'de'),
('hure', 'de'),
('hurensohn', 'de'),
('ische', 'de'),
('kackbratze', 'de'),
('kacke', 'de'),
('kacken', 'de'),
('kackwurst', 'de'),
('kampflesbe', 'de'),
('kanake', 'de'),
('kimme', 'de'),
('lummel', 'de'),
('milf', 'de'),
('mopse', 'de'),
('morgenlatte', 'de'),
('mose', 'de'),
('mufti', 'de'),
('muschi', 'de'),
('nackt', 'de'),
('neger', 'de'),
('nigger', 'de'),
('nippel', 'de'),
('nutte', 'de'),
('onanieren', 'de'),
('orgasmus', 'de'),
('penis', 'de'),
('pimmel', 'de'),
('pimpern', 'de'),
('pinkeln', 'de'),
('pissen', 'de'),
('pisser', 'de'),
('popel', 'de'),
('poppen', 'de'),
('porno', 'de'),
('reudig', 'de'),
('rosette', 'de'),
('schabracke', 'de'),
('schlampe', 'de'),
('scheiße', 'de'),
('scheisser', 'de'),
('schiesser', 'de'),
('schnackeln', 'de'),
('schwanzlutscher', 'de'),
('schwuchtel', 'de'),
('tittchen', 'de'),
('titten', 'de'),
('vogeln', 'de'),
('vollpfosten', 'de'),
('wichse', 'de'),
('wichsen', 'de'),
('wichser', 'de'),
('2g1c', 'en'),
('2 girls 1 cup', 'en'),
('acrotomophilia', 'en'),
('alabama hot pocket', 'en'),
('alaskan pipeline', 'en'),
('anal', 'en'),
('anilingus', 'en'),
('apeshit', 'en'),
('arsehole', 'en'),
('ass', 'en'),
('asshole', 'en'),
('assmunch', 'en'),
('auto erotic', 'en'),
('autoerotic', 'en'),
('babeland', 'en'),
('baby batter', 'en'),
('baby juice', 'en'),
('ball gag', 'en'),
('ball gravy', 'en'),
('ball kicking', 'en'),
('ball licking', 'en'),
('ball sack', 'en'),
('ball sucking', 'en'),
('bangbros', 'en'),
('bangbus', 'en'),
('bareback', 'en'),
('barely legal', 'en'),
('barenaked', 'en'),
('bastard', 'en'),
('bastardo', 'en'),
('bastinado', 'en'),
('bbw', 'en'),
('bdsm', 'en'),
('beaner', 'en'),
('beaners', 'en')
on conflict (word) do nothing;

insert into banned_words (word, lang) values
('beaver cleaver', 'en'),
('beaver lips', 'en'),
('beastiality', 'en'),
('bestiality', 'en'),
('big black', 'en'),
('big breasts', 'en'),
('big knockers', 'en'),
('big tits', 'en'),
('bimbos', 'en'),
('birdlock', 'en'),
('bitch', 'en'),
('bitches', 'en'),
('black cock', 'en'),
('blonde action', 'en'),
('blonde on blonde action', 'en'),
('blowjob', 'en'),
('blow job', 'en'),
('blow your load', 'en'),
('blue waffle', 'en'),
('blumpkin', 'en'),
('bollocks', 'en'),
('bondage', 'en'),
('boner', 'en'),
('boob', 'en'),
('boobs', 'en'),
('booty call', 'en'),
('brown showers', 'en'),
('brunette action', 'en'),
('bukkake', 'en'),
('bulldyke', 'en'),
('bullet vibe', 'en'),
('bullshit', 'en'),
('bung hole', 'en'),
('bunghole', 'en'),
('busty', 'en'),
('butt', 'en'),
('buttcheeks', 'en'),
('butthole', 'en'),
('camel toe', 'en'),
('camgirl', 'en'),
('camslut', 'en'),
('camwhore', 'en'),
('carpet muncher', 'en'),
('carpetmuncher', 'en'),
('chocolate rosebuds', 'en'),
('cialis', 'en'),
('circlejerk', 'en'),
('cleveland steamer', 'en'),
('clit', 'en'),
('clitoris', 'en'),
('clover clamps', 'en'),
('clusterfuck', 'en'),
('cocks', 'en'),
('coprolagnia', 'en'),
('coprophilia', 'en'),
('cornhole', 'en'),
('coon', 'en'),
('coons', 'en'),
('creampie', 'en'),
('cum', 'en'),
('cumming', 'en'),
('cumshot', 'en'),
('cumshots', 'en'),
('cunnilingus', 'en'),
('cunt', 'en'),
('darkie', 'en'),
('date rape', 'en'),
('daterape', 'en'),
('deep throat', 'en'),
('deepthroat', 'en'),
('dendrophilia', 'en'),
('dick', 'en'),
('dildo', 'en'),
('dingleberry', 'en'),
('dingleberries', 'en'),
('dirty pillows', 'en'),
('dirty sanchez', 'en'),
('doggie style', 'en'),
('doggiestyle', 'en'),
('doggy style', 'en'),
('doggystyle', 'en'),
('dog style', 'en'),
('dolcett', 'en'),
('domination', 'en'),
('dominatrix', 'en'),
('dommes', 'en'),
('donkey punch', 'en'),
('double dong', 'en'),
('double penetration', 'en'),
('dp action', 'en'),
('dry hump', 'en'),
('dvda', 'en'),
('eat my ass', 'en'),
('ecchi', 'en'),
('ejaculation', 'en'),
('erotic', 'en'),
('erotism', 'en'),
('escort', 'en'),
('eunuch', 'en'),
('fag', 'en'),
('faggot', 'en'),
('fecal', 'en'),
('felch', 'en'),
('fellatio', 'en'),
('feltch', 'en'),
('female squirting', 'en'),
('femdom', 'en'),
('figging', 'en'),
('fingerbang', 'en'),
('fingering', 'en'),
('fisting', 'en'),
('foot fetish', 'en'),
('footjob', 'en'),
('frotting', 'en'),
('fuck buttons', 'en'),
('fuckin', 'en'),
('fucking', 'en'),
('fucktards', 'en'),
('fudge packer', 'en'),
('fudgepacker', 'en'),
('futanari', 'en'),
('gangbang', 'en'),
('gang bang', 'en'),
('gay sex', 'en'),
('genitals', 'en'),
('giant cock', 'en'),
('girl on', 'en'),
('girl on top', 'en'),
('girls gone wild', 'en'),
('goatcx', 'en'),
('goatse', 'en'),
('god damn', 'en'),
('gokkun', 'en'),
('golden shower', 'en'),
('goodpoop', 'en'),
('goo girl', 'en'),
('goregasm', 'en'),
('grope', 'en'),
('group sex', 'en'),
('g-spot', 'en'),
('guro', 'en'),
('hand job', 'en'),
('handjob', 'en'),
('hard core', 'en'),
('hardcore', 'en'),
('hentai', 'en'),
('homoerotic', 'en'),
('honkey', 'en'),
('hooker', 'en'),
('horny', 'en'),
('hot carl', 'en'),
('hot chick', 'en'),
('how to kill', 'en'),
('how to murder', 'en'),
('huge fat', 'en'),
('humping', 'en'),
('incest', 'en'),
('intercourse', 'en'),
('jack off', 'en'),
('jail bait', 'en'),
('jailbait', 'en'),
('jelly donut', 'en'),
('jerk off', 'en'),
('jigaboo', 'en'),
('jiggaboo', 'en'),
('jiggerboo', 'en'),
('jizz', 'en'),
('juggs', 'en'),
('kike', 'en'),
('kinbaku', 'en'),
('kinkster', 'en'),
('kinky', 'en'),
('knobbing', 'en'),
('leather restraint', 'en'),
('leather straight jacket', 'en'),
('lemon party', 'en'),
('livesex', 'en'),
('lolita', 'en'),
('lovemaking', 'en'),
('make me come', 'en'),
('male squirting', 'en'),
('masturbate', 'en'),
('masturbating', 'en'),
('masturbation', 'en'),
('menage a trois', 'en'),
('missionary position', 'en'),
('mong', 'en'),
('motherfucker', 'en'),
('mound of venus', 'en'),
('mr hands', 'en'),
('muff diver', 'en'),
('muffdiving', 'en'),
('nambla', 'en'),
('nawashi', 'en'),
('negro', 'en'),
('neonazi', 'en'),
('nigga', 'en'),
('nig nog', 'en'),
('nimphomania', 'en'),
('nipple', 'en')
on conflict (word) do nothing;

insert into banned_words (word, lang) values
('nipples', 'en'),
('nsfw', 'en'),
('nsfw images', 'en'),
('nude', 'en'),
('nudity', 'en'),
('nutten', 'en'),
('nympho', 'en'),
('nymphomania', 'en'),
('octopussy', 'en'),
('omorashi', 'en'),
('one cup two girls', 'en'),
('one guy one jar', 'en'),
('orgasm', 'en'),
('orgy', 'en'),
('paedophile', 'en'),
('paki', 'en'),
('panties', 'en'),
('panty', 'en'),
('pedobear', 'en'),
('pedophile', 'en'),
('pegging', 'en'),
('phone sex', 'en'),
('piece of shit', 'en'),
('pikey', 'en'),
('pissing', 'en'),
('piss pig', 'en'),
('pisspig', 'en'),
('playboy', 'en'),
('pleasure chest', 'en'),
('pole smoker', 'en'),
('ponyplay', 'en'),
('poof', 'en'),
('poon', 'en'),
('poontang', 'en'),
('punany', 'en'),
('poop chute', 'en'),
('poopchute', 'en'),
('porn', 'en'),
('pornography', 'en'),
('prince albert piercing', 'en'),
('pthc', 'en'),
('pubes', 'en'),
('pussy', 'en'),
('queaf', 'en'),
('queef', 'en'),
('quim', 'en'),
('raghead', 'en'),
('raging boner', 'en'),
('rape', 'en'),
('raping', 'en'),
('rapist', 'en'),
('rectum', 'en'),
('reverse cowgirl', 'en'),
('rimjob', 'en'),
('rimming', 'en'),
('rosy palm', 'en'),
('rosy palm and her 5 sisters', 'en'),
('rusty trombone', 'en'),
('sadism', 'en'),
('santorum', 'en'),
('scat', 'en'),
('schlong', 'en'),
('scissoring', 'en'),
('semen', 'en'),
('sex', 'en'),
('sexcam', 'en'),
('sexo', 'en'),
('sexy', 'en'),
('sexual', 'en'),
('sexually', 'en'),
('sexuality', 'en'),
('shaved beaver', 'en'),
('shaved pussy', 'en'),
('shemale', 'en'),
('shibari', 'en'),
('shitblimp', 'en'),
('shitty', 'en'),
('shota', 'en'),
('shrimping', 'en'),
('skeet', 'en'),
('slanteye', 'en'),
('slut', 'en'),
('s&m', 'en'),
('smut', 'en'),
('snatch', 'en'),
('snowballing', 'en'),
('sodomize', 'en'),
('sodomy', 'en'),
('spastic', 'en'),
('spic', 'en'),
('splooge', 'en'),
('splooge moose', 'en'),
('spooge', 'en'),
('spread legs', 'en'),
('spunk', 'en'),
('strap on', 'en'),
('strapon', 'en'),
('strappado', 'en'),
('strip club', 'en'),
('style doggy', 'en'),
('suck', 'en'),
('sucks', 'en'),
('suicide girls', 'en'),
('sultry women', 'en'),
('swastika', 'en'),
('swinger', 'en'),
('tainted love', 'en'),
('taste my', 'en'),
('tea bagging', 'en'),
('threesome', 'en'),
('throating', 'en'),
('thumbzilla', 'en'),
('tied up', 'en'),
('tight white', 'en'),
('tit', 'en'),
('tits', 'en'),
('titties', 'en'),
('titty', 'en'),
('tongue in a', 'en'),
('topless', 'en'),
('tosser', 'en'),
('towelhead', 'en'),
('tranny', 'en'),
('tribadism', 'en'),
('tub girl', 'en'),
('tubgirl', 'en'),
('tushy', 'en'),
('twat', 'en'),
('twink', 'en'),
('twinkie', 'en'),
('two girls one cup', 'en'),
('undressing', 'en'),
('upskirt', 'en'),
('urethra play', 'en'),
('urophilia', 'en'),
('vagina', 'en'),
('venus mound', 'en'),
('viagra', 'en'),
('vibrator', 'en'),
('violet wand', 'en'),
('vorarephilia', 'en'),
('voyeur', 'en'),
('voyeurweb', 'en'),
('voyuer', 'en'),
('vulva', 'en'),
('wank', 'en'),
('wetback', 'en'),
('wet dream', 'en'),
('white power', 'en'),
('whore', 'en'),
('worldsex', 'en'),
('wrapping men', 'en'),
('wrinkled starfish', 'en'),
('xx', 'en'),
('xxx', 'en'),
('yaoi', 'en'),
('yellow showers', 'en'),
('yiffy', 'en'),
('zoophilia', 'en'),
('bugren', 'eo'),
('bugri', 'eo'),
('bugru', 'eo'),
('ciesulino', 'eo'),
('ciesulo', 'eo'),
('diofek', 'eo'),
('diofeka', 'eo'),
('fek', 'eo'),
('feken', 'eo'),
('fekfikanto', 'eo'),
('feklekulo', 'eo'),
('fekulo', 'eo'),
('fik', 'eo'),
('fikado', 'eo'),
('fikema', 'eo'),
('fikfek', 'eo'),
('fiki', 'eo'),
('fikigi', 'eo'),
('fikigu', 'eo'),
('fikilo', 'eo'),
('fikklauno', 'eo'),
('fikota', 'eo'),
('fiku', 'eo'),
('forfiki', 'eo'),
('forfikigu', 'eo'),
('forfiku', 'eo'),
('forfurzu', 'eo'),
('forpisi', 'eo'),
('forpisu', 'eo'),
('furzulo', 'eo'),
('kacen', 'eo'),
('kaco', 'eo'),
('kacsuculo', 'eo'),
('kojono', 'eo'),
('picen', 'eo'),
('pico', 'eo'),
('zamenfek', 'eo'),
('asesinato', 'es'),
('asno', 'es'),
('bollera', 'es'),
('cabron', 'es')
on conflict (word) do nothing;

insert into banned_words (word, lang) values
('caca', 'es'),
('chupada', 'es'),
('chupapollas', 'es'),
('chupeton', 'es'),
('concha', 'es'),
('concha de tu madre', 'es'),
('cono', 'es'),
('coprofagia', 'es'),
('culo', 'es'),
('drogas', 'es'),
('esperma', 'es'),
('fiesta de salchichas', 'es'),
('follador', 'es'),
('follar', 'es'),
('gilipichis', 'es'),
('gilipollas', 'es'),
('hacer una paja', 'es'),
('haciendo el amor', 'es'),
('heroina', 'es'),
('hija de puta', 'es'),
('hijaputa', 'es'),
('hijo de puta', 'es'),
('hijoputa', 'es'),
('idiota', 'es'),
('imbecil', 'es'),
('infierno', 'es'),
('jilipollas', 'es'),
('kapullo', 'es'),
('lameculos', 'es'),
('maciza', 'es'),
('macizorra', 'es'),
('maldito', 'es'),
('mamada', 'es'),
('marica', 'es'),
('maricon', 'es'),
('mariconazo', 'es'),
('martillo', 'es'),
('mierda', 'es'),
('nazi', 'es'),
('orina', 'es'),
('pedo', 'es'),
('pendejo', 'es'),
('pervertido', 'es'),
('pezon', 'es'),
('pinche', 'es'),
('prostituta', 'es'),
('puta', 'es'),
('racista', 'es'),
('ramera', 'es'),
('sadico', 'es'),
('sexo oral', 'es'),
('soplagaitas', 'es'),
('soplapollas', 'es'),
('tetas grandes', 'es'),
('tia buena', 'es'),
('travesti', 'es'),
('trio', 'es'),
('verga', 'es'),
('vete a la mierda', 'es'),
('اب کیر', 'fa'),
('ارگاسم', 'fa'),
('برهنه', 'fa'),
('پورن', 'fa'),
('پورنو', 'fa'),
('تجاوز', 'fa'),
('تخمی', 'fa'),
('جق', 'fa'),
('جقی', 'fa'),
('جلق', 'fa'),
('جنده', 'fa'),
('چوچول', 'fa'),
('حشر', 'fa'),
('حشری', 'fa'),
('داف', 'fa'),
('دودول', 'fa'),
('ساک زدن', 'fa'),
('سکس', 'fa'),
('سکس کردن', 'fa'),
('سکسی', 'fa'),
('سوپر', 'fa'),
('شق کردن', 'fa'),
('شهوت', 'fa'),
('شهوتی', 'fa'),
('شونبول', 'fa'),
('فیلم سوپر', 'fa'),
('کس', 'fa'),
('کس دادن', 'fa'),
('کس کردن', 'fa'),
('کسکش', 'fa'),
('کوس', 'fa'),
('کون', 'fa'),
('کون دادن', 'fa'),
('کون کردن', 'fa'),
('کونکش', 'fa'),
('کونی', 'fa'),
('کیر', 'fa'),
('کیری', 'fa'),
('لاپا', 'fa'),
('لاپایی', 'fa'),
('لاشی', 'fa'),
('لخت', 'fa'),
('لش', 'fa'),
('منی', 'fa'),
('هرزه', 'fa'),
('alfred nussi', 'fi'),
('bylsia', 'fi'),
('haahka', 'fi'),
('haista paska', 'fi'),
('haista vittu', 'fi'),
('hatullinen', 'fi'),
('helvetisti', 'fi'),
('hevonkuusi', 'fi'),
('hevonpaska', 'fi'),
('hevonperse', 'fi'),
('hevonvittu', 'fi'),
('hevonvitunperse', 'fi'),
('hitosti', 'fi'),
('hitto', 'fi'),
('huorata', 'fi'),
('hassia', 'fi'),
('juosten kustu', 'fi'),
('jutku', 'fi'),
('jutsku', 'fi'),
('jatka', 'fi'),
('kananpaska', 'fi'),
('koiranpaska', 'fi'),
('kuin esterin perseesta', 'fi'),
('kulli', 'fi'),
('kullinluikaus', 'fi'),
('kuppainen', 'fi'),
('kusaista', 'fi'),
('kuseksia', 'fi'),
('kusettaa', 'fi'),
('kusi', 'fi'),
('kusipaa', 'fi'),
('kusta', 'fi'),
('kyrpiintynyt', 'fi'),
('kyrpiintya', 'fi'),
('kyrpia', 'fi'),
('kyrpa', 'fi'),
('kyrpanaama', 'fi'),
('kyrvitys', 'fi'),
('lahtari', 'fi'),
('lutka', 'fi'),
('molo', 'fi'),
('molopaa', 'fi'),
('mulkero', 'fi'),
('mulkku', 'fi'),
('mulkvisti', 'fi'),
('muna', 'fi'),
('munapaa', 'fi'),
('munaton', 'fi'),
('mutakuono', 'fi'),
('mutiainen', 'fi'),
('naida', 'fi'),
('nainti', 'fi'),
('narttu', 'fi'),
('neekeri', 'fi'),
('nekru', 'fi'),
('nuolla persetta', 'fi'),
('nussia', 'fi'),
('nussija', 'fi'),
('nussinta', 'fi'),
('paljaalla', 'fi'),
('palli', 'fi'),
('pallit', 'fi'),
('paneskella', 'fi'),
('panettaa', 'fi'),
('panna', 'fi'),
('pano', 'fi'),
('pantava', 'fi'),
('paska', 'fi'),
('paskainen', 'fi'),
('paskamainen', 'fi'),
('paskanmarjat', 'fi'),
('paskantaa', 'fi'),
('paskapuhe', 'fi'),
('paskapaa', 'fi'),
('paskattaa', 'fi'),
('paskiainen', 'fi'),
('paskoa', 'fi'),
('pehko', 'fi'),
('pentele', 'fi'),
('perkele', 'fi'),
('perkeleesti', 'fi'),
('persaukinen', 'fi'),
('perse', 'fi'),
('perseennuolija', 'fi'),
('perseet olalla', 'fi'),
('persereika', 'fi'),
('perseaalio', 'fi'),
('perslapi', 'fi'),
('perspano', 'fi'),
('persvako', 'fi'),
('pilkunnussija', 'fi'),
('pillu', 'fi'),
('pillut', 'fi'),
('pipari', 'fi'),
('piru', 'fi'),
('pistaa', 'fi')
on conflict (word) do nothing;

insert into banned_words (word, lang) values
('pyllyvako', 'fi'),
('reika', 'fi'),
('reva', 'fi'),
('ripsipiirakka', 'fi'),
('runkata', 'fi'),
('runkkari', 'fi'),
('runkkaus', 'fi'),
('runkku', 'fi'),
('ryssa', 'fi'),
('rattipaa', 'fi'),
('saatanasti', 'fi'),
('suklaaosasto', 'fi'),
('tavara', 'fi'),
('toosa', 'fi'),
('tuhkaluukku', 'fi'),
('tumputtaa', 'fi'),
('turpasauna', 'fi'),
('tussu', 'fi'),
('tussukka', 'fi'),
('tussut', 'fi'),
('vakipano', 'fi'),
('vetaa kateen', 'fi'),
('viiksi', 'fi'),
('vittu', 'fi'),
('vittuilla', 'fi'),
('vittuilu', 'fi'),
('vittumainen', 'fi'),
('vittuuntua', 'fi'),
('vittuuntunut', 'fi'),
('vitun', 'fi'),
('vitusti', 'fi'),
('vituttaa', 'fi'),
('vitutus', 'fi'),
('apara', 'fi'),
('puta ka', 'fil'),
('putang ina', 'fil'),
('tang ina', 'fil'),
('tangina', 'fil'),
('burat', 'fil'),
('bayag', 'fil'),
('bobo', 'fil'),
('nognog', 'fil'),
('tanga', 'fil'),
('ulol', 'fil'),
('kantot', 'fil'),
('anak ka ng puta', 'fil'),
('jakol', 'fil'),
('baiser', 'fr'),
('bander', 'fr'),
('bigornette', 'fr'),
('bite', 'fr'),
('bitte', 'fr'),
('bloblos', 'fr'),
('bourre', 'fr'),
('bourree', 'fr'),
('brackmard', 'fr'),
('branlage', 'fr'),
('branler', 'fr'),
('branlette', 'fr'),
('branleur', 'fr'),
('branleuse', 'fr'),
('brouter le cresson', 'fr'),
('chatte', 'fr'),
('chiasse', 'fr'),
('chier', 'fr'),
('chiottes', 'fr'),
('clito', 'fr'),
('con', 'fr'),
('connard', 'fr'),
('connasse', 'fr'),
('conne', 'fr'),
('couilles', 'fr'),
('cramouille', 'fr'),
('cul', 'fr'),
('deconne', 'fr'),
('deconner', 'fr'),
('emmerdant', 'fr'),
('emmerder', 'fr'),
('emmerdeur', 'fr'),
('emmerdeuse', 'fr'),
('encule', 'fr'),
('enculee', 'fr'),
('enculeur', 'fr'),
('enculeurs', 'fr'),
('enfoire', 'fr'),
('enfoiree', 'fr'),
('etron', 'fr'),
('fille de pute', 'fr'),
('fils de pute', 'fr'),
('folle', 'fr'),
('foutre', 'fr'),
('gerbe', 'fr'),
('gerber', 'fr'),
('gouine', 'fr'),
('grande folle', 'fr'),
('grogniasse', 'fr'),
('gueule', 'fr'),
('jouir', 'fr'),
('la putain de ta mere', 'fr'),
('malpt', 'fr'),
('merde', 'fr'),
('merdeuse', 'fr'),
('merdeux', 'fr'),
('meuf', 'fr'),
('negre', 'fr'),
('nique ta mere', 'fr'),
('nique ta race', 'fr'),
('palucher', 'fr'),
('pedale', 'fr'),
('pede', 'fr'),
('peter', 'fr'),
('pipi', 'fr'),
('pouffiasse', 'fr'),
('pousse-crotte', 'fr'),
('putain', 'fr'),
('pute', 'fr'),
('ramoner', 'fr'),
('sac a foutre', 'fr'),
('sac a merde', 'fr'),
('salaud', 'fr'),
('salope', 'fr'),
('suce', 'fr'),
('tapette', 'fr'),
('tanche', 'fr'),
('teuch', 'fr'),
('tringler', 'fr'),
('trique', 'fr'),
('troncher', 'fr'),
('trou du cul', 'fr'),
('turlute', 'fr'),
('zigounette', 'fr'),
('zizi', 'fr'),
('aand', 'hi'),
('aandu', 'hi'),
('balatkar', 'hi'),
('balatkari', 'hi'),
('behen chod', 'hi'),
('beti chod', 'hi'),
('bhadva', 'hi'),
('bhadve', 'hi'),
('bhandve', 'hi'),
('bhangi', 'hi'),
('bhootni ke', 'hi'),
('bhosad', 'hi'),
('bhosadi ke', 'hi'),
('boobe', 'hi'),
('chakke', 'hi'),
('chinaal', 'hi'),
('chinki', 'hi'),
('chod', 'hi'),
('chodu', 'hi'),
('chodu bhagat', 'hi'),
('chooche', 'hi'),
('choochi', 'hi'),
('choope', 'hi'),
('choot', 'hi'),
('choot ke baal', 'hi'),
('chootia', 'hi'),
('chootiya', 'hi'),
('chuche', 'hi'),
('chuchi', 'hi'),
('chudaap', 'hi'),
('chudai khanaa', 'hi'),
('chudam chudai', 'hi'),
('chude', 'hi'),
('chut', 'hi'),
('chut ka chuha', 'hi'),
('chut ka churan', 'hi'),
('chut ka mail', 'hi'),
('chut ke baal', 'hi'),
('chut ke dhakkan', 'hi'),
('chut maarli', 'hi'),
('chutad', 'hi'),
('chutadd', 'hi'),
('chutan', 'hi'),
('chutia', 'hi'),
('chutiya', 'hi'),
('gaand', 'hi'),
('gaandfat', 'hi'),
('gaandmasti', 'hi'),
('gaandufad', 'hi'),
('gandfattu', 'hi'),
('gandu', 'hi'),
('gashti', 'hi'),
('gasti', 'hi'),
('ghassa', 'hi'),
('ghasti', 'hi'),
('gucchi', 'hi'),
('gucchu', 'hi'),
('harami', 'hi'),
('haramzade', 'hi'),
('hawas', 'hi'),
('hawas ke pujari', 'hi'),
('hijda', 'hi'),
('hijra', 'hi'),
('jhant', 'hi'),
('jhant chaatu', 'hi'),
('jhant ka keeda', 'hi'),
('jhant ke baal', 'hi'),
('jhant ke pissu', 'hi')
on conflict (word) do nothing;

insert into banned_words (word, lang) values
('jhantu', 'hi'),
('kamine', 'hi'),
('kaminey', 'hi'),
('kanjar', 'hi'),
('kutta', 'hi'),
('kutta kamina', 'hi'),
('kutte ki aulad', 'hi'),
('kutte ki jat', 'hi'),
('kuttiya', 'hi'),
('loda', 'hi'),
('lodu', 'hi'),
('lund', 'hi'),
('lund choos', 'hi'),
('lund ka bakkal', 'hi'),
('lund khajoor', 'hi'),
('lundtopi', 'hi'),
('lundure', 'hi'),
('maa ki chut', 'hi'),
('maal', 'hi'),
('madar chod', 'hi'),
('madarchod', 'hi'),
('madhavchod', 'hi'),
('mooh mein le', 'hi'),
('mutth', 'hi'),
('mutthal', 'hi'),
('najayaz', 'hi'),
('najayaz aulaad', 'hi'),
('najayaz paidaish', 'hi'),
('pataka', 'hi'),
('patakha', 'hi'),
('raand', 'hi'),
('randaap', 'hi'),
('randi', 'hi'),
('randi rona', 'hi'),
('saala', 'hi'),
('saala kutta', 'hi'),
('saali kutti', 'hi'),
('saali randi', 'hi'),
('suar', 'hi'),
('suar ke lund', 'hi'),
('suar ki aulad', 'hi'),
('tatte', 'hi'),
('tatti', 'hi'),
('teri maa ka bhosada', 'hi'),
('teri maa ka boba chusu', 'hi'),
('teri maa ki behenchod', 'hi'),
('teri maa ki chut', 'hi'),
('tharak', 'hi'),
('tharki', 'hi'),
('tu chuda', 'hi'),
('balfasz', 'hu'),
('balfaszok', 'hu'),
('balfaszokat', 'hu'),
('balfaszt', 'hu'),
('barmok', 'hu'),
('barmokat', 'hu'),
('barmot', 'hu'),
('barom', 'hu'),
('baszik', 'hu'),
('bazmeg', 'hu'),
('buksza', 'hu'),
('bukszak', 'hu'),
('bukszakat', 'hu'),
('bukszat', 'hu'),
('bur', 'hu'),
('burok', 'hu'),
('csocs', 'hu'),
('csocsok', 'hu'),
('csocsoket', 'hu'),
('csocsot', 'hu'),
('fasz', 'hu'),
('faszfej', 'hu'),
('faszfejek', 'hu'),
('faszfejeket', 'hu'),
('faszfejet', 'hu'),
('faszok', 'hu'),
('faszokat', 'hu'),
('faszt', 'hu'),
('fing', 'hu'),
('fingok', 'hu'),
('fingokat', 'hu'),
('fingot', 'hu'),
('franc', 'hu'),
('francok', 'hu'),
('francokat', 'hu'),
('francot', 'hu'),
('geci', 'hu'),
('gecibb', 'hu'),
('gecik', 'hu'),
('geciket', 'hu'),
('gecit', 'hu'),
('kibaszott', 'hu'),
('kibaszottabb', 'hu'),
('kur', 'hu'),
('kurafi', 'hu'),
('kurafik', 'hu'),
('kurafikat', 'hu'),
('kurafit', 'hu'),
('kurvak', 'hu'),
('kurvakat', 'hu'),
('kurvat', 'hu'),
('leggecibb', 'hu'),
('legkibaszottabb', 'hu'),
('legszarabb', 'hu'),
('marha', 'hu'),
('marhak', 'hu'),
('marhakat', 'hu'),
('marhat', 'hu'),
('megdoglik', 'hu'),
('pele', 'hu'),
('pelek', 'hu'),
('picsa', 'hu'),
('picsakat', 'hu'),
('picsat', 'hu'),
('pina', 'hu'),
('pinak', 'hu'),
('pinakat', 'hu'),
('pinat', 'hu'),
('pofa', 'hu'),
('pofakat', 'hu'),
('pofat', 'hu'),
('pocs', 'hu'),
('pocsok', 'hu'),
('pocsoket', 'hu'),
('pocsot', 'hu'),
('punci', 'hu'),
('puncik', 'hu'),
('segg', 'hu'),
('seggek', 'hu'),
('seggeket', 'hu'),
('segget', 'hu'),
('seggfej', 'hu'),
('seggfejek', 'hu'),
('seggfejeket', 'hu'),
('seggfejet', 'hu'),
('szajha', 'hu'),
('szajhak', 'hu'),
('szajhakat', 'hu'),
('szajhat', 'hu'),
('szar', 'hu'),
('szarabb', 'hu'),
('szarik', 'hu'),
('szarok', 'hu'),
('szarokat', 'hu'),
('szart', 'hu'),
('allupato', 'it'),
('ammucchiata', 'it'),
('anale', 'it'),
('arrapato', 'it'),
('arrusa', 'it'),
('arruso', 'it'),
('assatanato', 'it'),
('bagascia', 'it'),
('bagassa', 'it'),
('bagnarsi', 'it'),
('baldracca', 'it'),
('balle', 'it'),
('battere', 'it'),
('battona', 'it'),
('belino', 'it'),
('biga', 'it'),
('bocchinara', 'it'),
('bocchino', 'it'),
('bofilo', 'it'),
('boiata', 'it'),
('bordello', 'it'),
('brinca', 'it'),
('bucaiolo', 'it'),
('budiulo', 'it'),
('busone', 'it'),
('cacca', 'it'),
('caciocappella', 'it'),
('cadavere', 'it'),
('cagare', 'it'),
('cagata', 'it'),
('cagna', 'it'),
('casci', 'it'),
('cazzata', 'it'),
('cazzimma', 'it'),
('cazzo', 'it'),
('cesso', 'it'),
('cazzone', 'it'),
('checca', 'it'),
('chiappa', 'it'),
('chiavare', 'it'),
('chiavata', 'it'),
('ciospo', 'it'),
('ciucciami il cazzo', 'it'),
('coglione', 'it'),
('coglioni', 'it'),
('cornuto', 'it'),
('cozza', 'it'),
('culattina', 'it'),
('culattone', 'it'),
('ditalino', 'it'),
('fava', 'it'),
('femminuccia', 'it'),
('fica', 'it'),
('figa', 'it'),
('figlio di buona donna', 'it')
on conflict (word) do nothing;

insert into banned_words (word, lang) values
('figlio di puttana', 'it'),
('figone', 'it'),
('finocchio', 'it'),
('fottere', 'it'),
('fottersi', 'it'),
('fracicone', 'it'),
('fregna', 'it'),
('frocio', 'it'),
('froscio', 'it'),
('goldone', 'it'),
('guardone', 'it'),
('imbecille', 'it'),
('incazzarsi', 'it'),
('incoglionirsi', 'it'),
('ingoio', 'it'),
('leccaculo', 'it'),
('lecchino', 'it'),
('lofare', 'it'),
('loffa', 'it'),
('loffare', 'it'),
('mannaggia', 'it'),
('merda', 'it'),
('merdata', 'it'),
('merdoso', 'it'),
('mignotta', 'it'),
('minchia', 'it'),
('minchione', 'it'),
('mona', 'it'),
('monta', 'it'),
('montare', 'it'),
('mussa', 'it'),
('nave scuola', 'it'),
('nerchia', 'it'),
('padulo', 'it'),
('palle', 'it'),
('palloso', 'it'),
('patacca', 'it'),
('patonza', 'it'),
('pecorina', 'it'),
('pesce', 'it'),
('picio', 'it'),
('pincare', 'it'),
('pippa', 'it'),
('pinnolone', 'it'),
('pippone', 'it'),
('pirla', 'it'),
('pisciare', 'it'),
('piscio', 'it'),
('pisello', 'it'),
('pistolotto', 'it'),
('pomiciare', 'it'),
('pompa', 'it'),
('pompino', 'it'),
('porca', 'it'),
('porca madonna', 'it'),
('porca miseria', 'it'),
('porca puttana', 'it'),
('porco', 'it'),
('porco due', 'it'),
('porco zio', 'it'),
('potta', 'it'),
('puppami', 'it'),
('puttana', 'it'),
('quaglia', 'it'),
('recchione', 'it'),
('regina', 'it'),
('rincoglionire', 'it'),
('rizzarsi', 'it'),
('rompiballe', 'it'),
('rompipalle', 'it'),
('ruffiano', 'it'),
('sbattere', 'it'),
('sbattersi', 'it'),
('sborra', 'it'),
('sborrata', 'it'),
('sborrone', 'it'),
('sbrodolata', 'it'),
('scopare', 'it'),
('scopata', 'it'),
('scorreggiare', 'it'),
('sega', 'it'),
('slinguare', 'it'),
('slinguata', 'it'),
('smandrappata', 'it'),
('soccia', 'it'),
('socmel', 'it'),
('sorca', 'it'),
('spagnola', 'it'),
('spompinare', 'it'),
('sticchio', 'it'),
('stronza', 'it'),
('stronzata', 'it'),
('stronzo', 'it'),
('succhiami', 'it'),
('succhione', 'it'),
('sveltina', 'it'),
('sverginare', 'it'),
('tarzanello', 'it'),
('terrone', 'it'),
('testa di cazzo', 'it'),
('tette', 'it'),
('tirare', 'it'),
('topa', 'it'),
('troia', 'it'),
('trombare', 'it'),
('vacca', 'it'),
('vaffanculo', 'it'),
('vangare', 'it'),
('zinne', 'it'),
('zio cantante', 'it'),
('zoccola', 'it'),
('3p', 'ja'),
('g スホット', 'ja'),
('s ＆ m', 'ja'),
('sm', 'ja'),
('sm女王', 'ja'),
('アシアのかわいい女の子', 'ja'),
('アスホール', 'ja'),
('アナリンクス', 'ja'),
('アナル', 'ja'),
('いたすら', 'ja'),
('イラマチオ', 'ja'),
('エクスタシー', 'ja'),
('エスコート', 'ja'),
('エッチ', 'ja'),
('エロティスム', 'ja'),
('エロティック', 'ja'),
('オーカスム', 'ja'),
('オカマ', 'ja'),
('おしっこ', 'ja'),
('おしり', 'ja'),
('オシリ', 'ja'),
('おしりのあな', 'ja'),
('おっはい', 'ja'),
('オッハイ', 'ja'),
('オナニー', 'ja'),
('オマンコ', 'ja'),
('おもらし', 'ja'),
('お尻', 'ja'),
('カーマスートラ', 'ja'),
('カント', 'ja'),
('クリトリス', 'ja'),
('クルーフ・セックス', 'ja'),
('クロ', 'ja'),
('クンニリンクス', 'ja'),
('ケイ・セックス', 'ja'),
('ケイホーイ', 'ja'),
('コールテンシャワー', 'ja'),
('コカイン', 'ja'),
('コックン', 'ja'),
('サティスム', 'ja'),
('しはり', 'ja'),
('スウィンカー', 'ja'),
('スカートの中', 'ja'),
('スカトロ', 'ja'),
('ストラッフオン', 'ja'),
('ストリッフ劇場', 'ja'),
('スラット', 'ja'),
('スリット', 'ja'),
('セクシーな', 'ja'),
('セクシーな 10 代', 'ja'),
('セックス', 'ja'),
('ソトミー', 'ja'),
('ちんこ', 'ja'),
('ティーフ・スロート', 'ja'),
('ティック', 'ja'),
('ティルト', 'ja'),
('テートレイフ', 'ja'),
('テフ', 'ja'),
('テレフォンセックス', 'ja'),
('トックスタイル', 'ja'),
('トッフレス', 'ja'),
('なめ', 'ja'),
('ニカー', 'ja'),
('ヌート', 'ja'),
('ネオ・ナチ', 'ja'),
('ハートコア', 'ja'),
('ハイハン', 'ja'),
('ハイフレーター', 'ja'),
('ハック・スタイル', 'ja'),
('ハンティー', 'ja'),
('ヒッチ', 'ja'),
('ファック', 'ja'),
('ファンタシー', 'ja'),
('フィスト', 'ja'),
('フェティッシュ', 'ja'),
('フェラチオ', 'ja'),
('ふたなり', 'ja'),
('ふっかけ', 'ja'),
('フック', 'ja'),
('フリンス アルハート ヒアス', 'ja'),
('フレイホーイ', 'ja'),
('ヘアハック', 'ja'),
('ヘニス', 'ja'),
('ヘニスハント', 'ja'),
('ホーイスラフ', 'ja'),
('ホールキャク', 'ja'),
('ほっちゃり', 'ja'),
('ホモ', 'ja'),
('ホルノ', 'ja')
on conflict (word) do nothing;

insert into banned_words (word, lang) values
('ホルノクラフィー', 'ja'),
('ホンテーシ', 'ja'),
('マサー・ファッカー', 'ja'),
('マスターヘーション', 'ja'),
('まんこ', 'ja'),
('やおい', 'ja'),
('やりまん', 'ja'),
('ラティーナ', 'ja'),
('ラハー', 'ja'),
('ランシェリー', 'ja'),
('レイフ', 'ja'),
('レスヒアン', 'ja'),
('ローター', 'ja'),
('ロリータ', 'ja'),
('淫乱', 'ja'),
('陰毛', 'ja'),
('革抑制', 'ja'),
('騎上位', 'ja'),
('巨根', 'ja'),
('巨乳', 'ja'),
('強姦犯', 'ja'),
('玉なめ', 'ja'),
('玉舐め', 'ja'),
('緊縛', 'ja'),
('近親相姦', 'ja'),
('嫌い', 'ja'),
('後背位', 'ja'),
('合意の性交', 'ja'),
('拷問', 'ja'),
('殺し方', 'ja'),
('殺人事件', 'ja'),
('殺人方法', 'ja'),
('支配', 'ja'),
('児童性虐待', 'ja'),
('自己愛性', 'ja'),
('射精', 'ja'),
('手コキ', 'ja'),
('獣姦', 'ja'),
('女の子', 'ja'),
('女王様', 'ja'),
('女子高生', 'ja'),
('女装', 'ja'),
('新しいホルノ', 'ja'),
('人妻', 'ja'),
('人種', 'ja'),
('性交', 'ja'),
('正常位', 'ja'),
('生殖器', 'ja'),
('精液', 'ja'),
('挿入', 'ja'),
('足フェチ', 'ja'),
('足を広ける', 'ja'),
('大陰唇', 'ja'),
('脱衣', 'ja'),
('茶色のシャワー', 'ja'),
('中出し', 'ja'),
('潮吹き女', 'ja'),
('潮吹き男性', 'ja'),
('直腸', 'ja'),
('剃毛', 'ja'),
('貞操帯', 'ja'),
('奴隷', 'ja'),
('二穴', 'ja'),
('乳首', 'ja'),
('尿道フレイ', 'ja'),
('覗き', 'ja'),
('売春婦', 'ja'),
('縛り', 'ja'),
('噴出', 'ja'),
('糞尿愛好症', 'ja'),
('糞便', 'ja'),
('平手打ち', 'ja'),
('変態', 'ja'),
('勃起する', 'ja'),
('夢精', 'ja'),
('毛深い', 'ja'),
('誘惑', 'ja'),
('幼児性愛者', 'ja'),
('裸の女性', 'ja'),
('乱交', 'ja'),
('両性', 'ja'),
('両性具有', 'ja'),
('両刀', 'ja'),
('輪姦', 'ja'),
('宦官', 'ja'),
('肛門', 'ja'),
('abbuc', 'kab'),
('aεettud', 'kab'),
('aheccun', 'kab'),
('taheccunt', 'kab'),
('axuzzid', 'kab'),
('asxuzed', 'kab'),
('qqu', 'kab'),
('qquɣ', 'kab'),
('qqiɣ', 'kab'),
('qqan', 'kab'),
('qqant', 'kab'),
('tteqqun', 'kab'),
('tteqqunt', 'kab'),
('aqerqur', 'kab'),
('ajehnid', 'kab'),
('awellaq', 'kab'),
('iwellaqen', 'kab'),
('iheccan', 'kab'),
('iheccunen', 'kab'),
('uqan', 'kab'),
('taxna', 'kab'),
('강간', 'ko'),
('개새끼', 'ko'),
('개자식', 'ko'),
('개좆', 'ko'),
('개차반', 'ko'),
('거유', 'ko'),
('계집년', 'ko'),
('고자', 'ko'),
('근친', 'ko'),
('노모', 'ko'),
('니기미', 'ko'),
('뒤질래', 'ko'),
('딸딸이', 'ko'),
('때씹', 'ko'),
('또라이', 'ko'),
('뙤놈', 'ko'),
('로리타', 'ko'),
('망가', 'ko'),
('몰카', 'ko'),
('미친', 'ko'),
('미친새끼', 'ko'),
('바바리맨', 'ko'),
('변태', 'ko'),
('병신', 'ko'),
('보지', 'ko'),
('불알', 'ko'),
('빠구리', 'ko'),
('사까시', 'ko'),
('섹스', 'ko'),
('스와핑', 'ko'),
('쌍놈', 'ko'),
('씨발', 'ko'),
('씨발놈', 'ko'),
('씨팔', 'ko'),
('씹물', 'ko'),
('씹빨', 'ko'),
('씹새끼', 'ko'),
('씹알', 'ko'),
('씹창', 'ko'),
('씹팔', 'ko'),
('암캐', 'ko'),
('애자', 'ko'),
('야동', 'ko'),
('야사', 'ko'),
('야애니', 'ko'),
('엄창', 'ko'),
('에로', 'ko'),
('염병', 'ko'),
('옘병', 'ko'),
('유모', 'ko'),
('육갑', 'ko'),
('은꼴', 'ko'),
('자위', 'ko'),
('자지', 'ko'),
('잡년', 'ko'),
('종간나', 'ko'),
('좆만', 'ko'),
('죽일년', 'ko'),
('쥐좆', 'ko'),
('직촬', 'ko'),
('짱깨', 'ko'),
('쪽바리', 'ko'),
('창녀', 'ko'),
('포르노', 'ko'),
('하드코어', 'ko'),
('호로', 'ko'),
('화냥년', 'ko'),
('후레아들', 'ko'),
('후장', 'ko'),
('희쭈그리', 'ko'),
('aardappels afgieten', 'nl'),
('achter het raam zitten', 'nl'),
('afberen', 'nl'),
('aflebberen', 'nl'),
('afrossen', 'nl'),
('afrukken', 'nl'),
('aftrekken', 'nl'),
('afwerkplaats', 'nl'),
('afzeiken', 'nl'),
('afzuigen', 'nl'),
('een halve man en een paardekop', 'nl'),
('anita', 'nl'),
('asbak', 'nl'),
('aso', 'nl'),
('bagger schijten', 'nl'),
('balen', 'nl'),
('bedonderen', 'nl'),
('befborstel', 'nl'),
('beffen', 'nl'),
('bekken', 'nl'),
('belazeren', 'nl'),
('besodemieterd zijn', 'nl'),
('besodemieteren', 'nl')
on conflict (word) do nothing;

insert into banned_words (word, lang) values
('beurt', 'nl'),
('boemelen', 'nl'),
('boerelul', 'nl'),
('boerenpummel', 'nl'),
('bokkelul', 'nl'),
('botergeil', 'nl'),
('broekhoesten', 'nl'),
('brugpieper', 'nl'),
('buffelen', 'nl'),
('buiten de pot piesen', 'nl'),
('das kloten van de bok', 'nl'),
('de ballen', 'nl'),
('de hoer spelen', 'nl'),
('de hond uitlaten', 'nl'),
('de koffer induiken', 'nl'),
('del', 'nl'),
('de pijp uitgaan', 'nl'),
('dombo', 'nl'),
('draaikont', 'nl'),
('driehoog achter wonen', 'nl'),
('drol', 'nl'),
('drooggeiler', 'nl'),
('droogkloot', 'nl'),
('een beurt geven', 'nl'),
('een nummertje maken', 'nl'),
('een wip maken', 'nl'),
('eikel', 'nl'),
('engerd', 'nl'),
('flamoes', 'nl'),
('flikken', 'nl'),
('flikker', 'nl'),
('gadverdamme', 'nl'),
('galbak', 'nl'),
('gat', 'nl'),
('gedoogzone', 'nl'),
('geilneef', 'nl'),
('gesodemieter', 'nl'),
('godverdomme', 'nl'),
('graftak', 'nl'),
('gras maaien', 'nl'),
('gratenkut', 'nl'),
('greppeldel', 'nl'),
('griet', 'nl'),
('hoempert', 'nl'),
('hoer', 'nl'),
('hoerenbuurt', 'nl'),
('hoerenloper', 'nl'),
('hoerig', 'nl'),
('hol', 'nl'),
('hufter', 'nl'),
('huisdealer', 'nl'),
('johny', 'nl'),
('kanen', 'nl'),
('kettingzeug', 'nl'),
('klaarkomen', 'nl'),
('klerebeer', 'nl'),
('klojo', 'nl'),
('klooien', 'nl'),
('klootjesvolk', 'nl'),
('klootoog', 'nl'),
('klootzak', 'nl'),
('kloten', 'nl'),
('knor', 'nl'),
('kont', 'nl'),
('kontneuken', 'nl'),
('krentekakker', 'nl'),
('kut', 'nl'),
('kuttelikkertje', 'nl'),
('kwakkie', 'nl'),
('liefdesgrot', 'nl'),
('lul', 'nl'),
('lul-de-behanger', 'nl'),
('lulhannes', 'nl'),
('mafketel', 'nl'),
('matennaaier', 'nl'),
('matje', 'nl'),
('mof', 'nl'),
('muts', 'nl'),
('naaien', 'nl'),
('naakt', 'nl'),
('neuken', 'nl'),
('neukstier', 'nl'),
('nicht', 'nl'),
('oetlul', 'nl'),
('opgeilen', 'nl'),
('opkankeren', 'nl'),
('oprotten', 'nl'),
('opsodemieteren', 'nl'),
('op zn hondjes', 'nl'),
('op zn sodemieter geven', 'nl'),
('opzouten', 'nl'),
('ouwehoer', 'nl'),
('ouwehoeren', 'nl'),
('ouwe rukker', 'nl'),
('paal', 'nl'),
('paardelul', 'nl'),
('palen', 'nl'),
('penoze', 'nl'),
('piesen', 'nl'),
('pijpbekkieg', 'nl'),
('pijpen', 'nl'),
('pleurislaaier', 'nl'),
('poep', 'nl'),
('poepen', 'nl'),
('poot', 'nl'),
('portiekslet', 'nl'),
('pot', 'nl'),
('potverdorie', 'nl'),
('publiciteitsgeil', 'nl'),
('raaskallen', 'nl'),
('reet', 'nl'),
('reetridder', 'nl'),
('reet trappen, voor zijn', 'nl'),
('remsporen', 'nl'),
('reutelen', 'nl'),
('rothoer', 'nl'),
('rotzak', 'nl'),
('rukhond', 'nl'),
('rukken', 'nl'),
('schatje', 'nl'),
('schijt', 'nl'),
('schijten', 'nl'),
('schoft', 'nl'),
('schuinsmarcheerder', 'nl'),
('slempen', 'nl'),
('slet', 'nl'),
('sletterig', 'nl'),
('slik mijn zaad', 'nl'),
('snol', 'nl'),
('spuiten', 'nl'),
('standje', 'nl'),
('standje-69', 'nl'),
('stoephoer', 'nl'),
('stootje', 'nl'),
('stront', 'nl'),
('sufferd', 'nl'),
('tapijtnek', 'nl'),
('teef', 'nl'),
('temeier', 'nl'),
('teringlijer', 'nl'),
('toeter', 'nl'),
('tongzoeng', 'nl'),
('triootjeg', 'nl'),
('trottoir prostituee', 'nl'),
('trottoirteef', 'nl'),
('vergallen', 'nl'),
('verkloten', 'nl'),
('verneuken', 'nl'),
('viespeuk', 'nl'),
('vingeren', 'nl'),
('vleesroos', 'nl'),
('voor jan lul', 'nl'),
('voor jan-met-de-korte-achternaam', 'nl'),
('watje', 'nl'),
('welzijnsmafia', 'nl'),
('wijf', 'nl'),
('wippen', 'nl'),
('wuftje', 'nl'),
('zaadje', 'nl'),
('zakkenwasser', 'nl'),
('zeiken', 'nl'),
('zeiker', 'nl'),
('zuigen', 'nl'),
('zuiplap', 'nl'),
('dritt', 'no'),
('drittsekk', 'no'),
('faen', 'no'),
('faen i helvete', 'no'),
('fan', 'no'),
('fanken', 'no'),
('fitte', 'no'),
('forbanna', 'no'),
('forbannet', 'no'),
('forjævlig', 'no'),
('fy faen', 'no'),
('føkk', 'no'),
('føkka', 'no'),
('føkkings', 'no'),
('jævla', 'no'),
('jævlig', 'no'),
('helvete', 'no'),
('helvetet', 'no'),
('kuk', 'no'),
('kukene', 'no'),
('kuker', 'no'),
('morraknuller', 'no'),
('morrapuler', 'no'),
('pakkis', 'no'),
('pikk', 'no'),
('pokker', 'no'),
('ræva', 'no'),
('ræven', 'no'),
('satan', 'no'),
('sinnsykt', 'no'),
('skitt', 'no'),
('sotrør', 'no'),
('stapikk', 'no'),
('stapikkene', 'no'),
('stapikker', 'no'),
('svartheiteste', 'no')
on conflict (word) do nothing;

insert into banned_words (word, lang) values
('burdel', 'pl'),
('burdelmama', 'pl'),
('chujnia', 'pl'),
('ciota', 'pl'),
('cipa', 'pl'),
('cyc', 'pl'),
('dmuchac', 'pl'),
('do kurwy nedzy', 'pl'),
('dupa', 'pl'),
('dupek', 'pl'),
('duperele', 'pl'),
('dziwka', 'pl'),
('fiut', 'pl'),
('gowno', 'pl'),
('gowno prawda', 'pl'),
('huj', 'pl'),
('huj ci w dupe', 'pl'),
('jajco', 'pl'),
('jajko', 'pl'),
('ja pierdole', 'pl'),
('jebac', 'pl'),
('jebany', 'pl'),
('kurwa', 'pl'),
('kurwy', 'pl'),
('kutafon', 'pl'),
('kutas', 'pl'),
('lizac pałe', 'pl'),
('obciagac chuja', 'pl'),
('obciagac fiuta', 'pl'),
('obciagac loda', 'pl'),
('pieprzyc', 'pl'),
('pierdolec', 'pl'),
('pierdolic', 'pl'),
('pierdolnac', 'pl'),
('pierdolniety', 'pl'),
('pierdoła', 'pl'),
('pierdziec', 'pl'),
('pojeb', 'pl'),
('pojebany', 'pl'),
('popierdolony', 'pl'),
('robic loda', 'pl'),
('ruchac', 'pl'),
('rzygac', 'pl'),
('skurwysyn', 'pl'),
('sraczka', 'pl'),
('srac', 'pl'),
('suka', 'pl'),
('syf', 'pl'),
('wkurwiac', 'pl'),
('zajebisty', 'pl'),
('aborto', 'pt'),
('amador', 'pt'),
('aranha', 'pt'),
('ariano', 'pt'),
('balalao', 'pt'),
('bicha', 'pt'),
('biscate', 'pt'),
('bissexual', 'pt'),
('boceta', 'pt'),
('bosta', 'pt'),
('braulio de borracha', 'pt'),
('bumbum', 'pt'),
('burro', 'pt'),
('cabrao', 'pt'),
('cacete', 'pt'),
('cagar', 'pt'),
('camisinha', 'pt'),
('caralho', 'pt'),
('cerveja', 'pt'),
('chochota', 'pt'),
('chupar', 'pt'),
('cocaina', 'pt'),
('coito', 'pt'),
('colhoes', 'pt'),
('comer', 'pt'),
('cona', 'pt'),
('consolo', 'pt'),
('corno', 'pt'),
('cu', 'pt'),
('dar o rabo', 'pt'),
('dum raio', 'pt'),
('esporra', 'pt'),
('filho da puta', 'pt'),
('foda', 'pt'),
('foda-se', 'pt'),
('foder', 'pt'),
('frango assado', 'pt'),
('gozar', 'pt'),
('grelho', 'pt'),
('heterosexual', 'pt'),
('homem gay', 'pt'),
('homoerotico', 'pt'),
('homosexual', 'pt'),
('inferno', 'pt'),
('lesbica', 'pt'),
('mama', 'pt'),
('paneleiro', 'pt'),
('passar um cheque', 'pt'),
('pau', 'pt'),
('peidar', 'pt'),
('pinto', 'pt'),
('porra', 'pt'),
('puta que pariu', 'pt'),
('puta que te pariu', 'pt'),
('queca', 'pt'),
('sacanagem', 'pt'),
('saco', 'pt'),
('torneira', 'pt'),
('transar', 'pt'),
('vadia', 'pt'),
('vai-te foder', 'pt'),
('vai tomar no cu', 'pt'),
('veado', 'pt'),
('vibrador', 'pt'),
('xana', 'pt'),
('xochota', 'pt'),
('bychara', 'ru'),
('byk', 'ru'),
('chernozhopyi', 'ru'),
('dolboyeb', 'ru'),
('ebalnik', 'ru'),
('ebalo', 'ru'),
('ebalom schelkat', 'ru'),
('gol', 'ru'),
('mudack', 'ru'),
('opizdenet', 'ru'),
('ostoeblo', 'ru'),
('ostokhuitelno', 'ru'),
('otebis', 'ru'),
('otmudohat', 'ru'),
('otpizdit', 'ru'),
('otsosi', 'ru'),
('padlo', 'ru'),
('pedik', 'ru'),
('perdet', 'ru'),
('petuh', 'ru'),
('pidar gnoinyj', 'ru'),
('pizdato', 'ru'),
('pizdatyi', 'ru'),
('pizdet', 'ru'),
('pizdetc', 'ru'),
('pizdoi nakrytsja', 'ru'),
('pizduk', 'ru'),
('piz`dyulina', 'ru'),
('podi kuevo', 'ru'),
('poeben', 'ru'),
('poimat na konchik', 'ru'),
('poiti posrat', 'ru'),
('po khuy', 'ru'),
('poluchit pizdy', 'ru'),
('pososi moyu konfetku', 'ru'),
('prissat', 'ru'),
('proebat', 'ru'),
('promudobladsksya pizdoproebina', 'ru'),
('propezdoloch', 'ru'),
('prosrat', 'ru'),
('raspeezdeyi', 'ru'),
('raspizdatyi', 'ru'),
('razyebuy', 'ru'),
('razyoba', 'ru'),
('sebatsya', 'ru'),
('shalava', 'ru'),
('styervo', 'ru'),
('sukin syn', 'ru'),
('svodit posrat', 'ru'),
('svoloch', 'ru'),
('trakhatsya', 'ru'),
('trimandoblydskiy pizdoproyob', 'ru'),
('ublyudok', 'ru'),
('uboy', 'ru'),
('uebitsche', 'ru'),
('vafla', 'ru'),
('vafli lovit', 'ru'),
('v pizdu', 'ru'),
('vyperdysh', 'ru'),
('vzdrochennyi', 'ru'),
('yeb vas', 'ru'),
('zaebat', 'ru'),
('zaebis', 'ru'),
('zalupa', 'ru'),
('zalupat', 'ru'),
('zasranetc', 'ru'),
('zassat', 'ru'),
('zloebuchy', 'ru'),
('бзденок', 'ru'),
('блядки', 'ru'),
('блядовать', 'ru'),
('блядство', 'ru'),
('блядь', 'ru'),
('бугор', 'ru'),
('во пизду', 'ru'),
('встать раком', 'ru'),
('выебываться', 'ru'),
('гандон', 'ru'),
('говно', 'ru'),
('говнюк', 'ru'),
('голыи', 'ru'),
('дать пизды', 'ru'),
('дерьмо', 'ru'),
('дрочить', 'ru')
on conflict (word) do nothing;

insert into banned_words (word, lang) values
('другои дразнится', 'ru'),
('ебарь', 'ru'),
('ебать', 'ru'),
('ебать-копать', 'ru'),
('ебло', 'ru'),
('ебнуть', 'ru'),
('еб твою мать', 'ru'),
('жопа', 'ru'),
('жополиз', 'ru'),
('играть на кожанои флеите', 'ru'),
('измудохать', 'ru'),
('каждыи дрочит как он хочет', 'ru'),
('какая разница', 'ru'),
('как два пальца обоссать', 'ru'),
('курите мою трубку', 'ru'),
('лысого в кулаке гонять', 'ru'),
('малофья', 'ru'),
('манда', 'ru'),
('мандавошка', 'ru'),
('мент', 'ru'),
('муда', 'ru'),
('мудило', 'ru'),
('мудозвон', 'ru'),
('наебать', 'ru'),
('наебениться', 'ru'),
('наебнуться', 'ru'),
('на фиг', 'ru'),
('на хуи', 'ru'),
('на хую вертеть', 'ru'),
('на хуя', 'ru'),
('нахуячиться', 'ru'),
('невебенныи', 'ru'),
('не ебет', 'ru'),
('ни за хуи собачу', 'ru'),
('ни хуя', 'ru'),
('обнаженныи', 'ru'),
('обоссаться можно', 'ru'),
('один ебется', 'ru'),
('опесдол', 'ru'),
('офигеть', 'ru'),
('охуеть', 'ru'),
('охуительно', 'ru'),
('половое сношение', 'ru'),
('секс', 'ru'),
('сиськи', 'ru'),
('спиздить', 'ru'),
('срать', 'ru'),
('ссать', 'ru'),
('траxать', 'ru'),
('ты мне ваньку не валяи', 'ru'),
('фига', 'ru'),
('хапать', 'ru'),
('хер с неи', 'ru'),
('хер с ним', 'ru'),
('хохол', 'ru'),
('хрен', 'ru'),
('хуево', 'ru'),
('хуевыи', 'ru'),
('хуем груши околачивать', 'ru'),
('хуеплет', 'ru'),
('хуило', 'ru'),
('хуинеи страдать', 'ru'),
('хуиня', 'ru'),
('хуи', 'ru'),
('хуинуть', 'ru'),
('хуи пинать', 'ru'),
('arsle', 'sv'),
('brutta', 'sv'),
('discofitta', 'sv'),
('dra at helvete', 'sv'),
('fitta', 'sv'),
('fittig', 'sv'),
('for helvete', 'sv'),
('hard', 'sv'),
('javlar', 'sv'),
('knulla', 'sv'),
('kuksas', 'sv'),
('kotthuvud', 'sv'),
('kottnacke', 'sv'),
('moona', 'sv'),
('moonade', 'sv'),
('moonar', 'sv'),
('moonat', 'sv'),
('mutta', 'sv'),
('olla', 'sv'),
('pitt', 'sv'),
('prutt', 'sv'),
('pok', 'sv'),
('runka', 'sv'),
('rov', 'sv'),
('rovhal', 'sv'),
('rovknulla', 'sv'),
('skita', 'sv'),
('skit ner dig', 'sv'),
('skaggbiff', 'sv'),
('snedfitta', 'sv'),
('snefitta', 'sv'),
('stake', 'sv'),
('subba', 'sv'),
('sas', 'sv'),
('satta pa', 'sv'),
('tusan', 'sv'),
('กระดอ', 'th'),
('กระเดา', 'th'),
('กระหร', 'th'),
('กะป', 'th'),
('ก', 'th'),
('ข', 'th'),
('ควย', 'th'),
('จม', 'th'),
('จ', 'th'),
('เจก', 'th'),
('เจยว', 'th'),
('ดอกทอง', 'th'),
('ตอแหล', 'th'),
('ตด', 'th'),
('นาแตก', 'th'),
('มง', 'th'),
('แมง', 'th'),
('เยด', 'th'),
('รตด', 'th'),
('ลางตเยน', 'th'),
('สนตน', 'th'),
('สด', 'th'),
('เสอก', 'th'),
('หญงชาตชว', 'th'),
('หลง', 'th'),
('หา', 'th'),
('ห', 'th'),
('เหย', 'th'),
('อมนกเขา', 'th'),
('ไอควาย', 'th'),
('am', 'tr'),
('amcıga', 'tr'),
('amcıgı', 'tr'),
('amcıgın', 'tr'),
('amcık', 'tr'),
('amcıklar', 'tr'),
('amcıklara', 'tr'),
('amcıklarda', 'tr'),
('amcıklardan', 'tr'),
('amcıkları', 'tr'),
('amcıkların', 'tr'),
('amcıkta', 'tr'),
('amcıktan', 'tr'),
('amı', 'tr'),
('amlar', 'tr'),
('cingene', 'tr'),
('cingenede', 'tr'),
('cingeneden', 'tr'),
('cingeneler', 'tr'),
('cingenelerde', 'tr'),
('cingenelerden', 'tr'),
('cingenelere', 'tr'),
('cingeneleri', 'tr'),
('cingenelerin', 'tr'),
('cingenenin', 'tr'),
('cingeneye', 'tr'),
('cingeneyi', 'tr'),
('got', 'tr'),
('gote', 'tr'),
('gotler', 'tr'),
('gotlerde', 'tr'),
('gotlerden', 'tr'),
('gotlere', 'tr'),
('gotleri', 'tr'),
('gotlerin', 'tr'),
('gotte', 'tr'),
('gotten', 'tr'),
('gotu', 'tr'),
('gotun', 'tr'),
('gotveren', 'tr'),
('gotverende', 'tr'),
('gotverenden', 'tr'),
('gotverene', 'tr'),
('gotvereni', 'tr'),
('gotverenin', 'tr'),
('gotverenler', 'tr'),
('gotverenlerde', 'tr'),
('gotverenlerden', 'tr'),
('gotverenlere', 'tr'),
('gotverenleri', 'tr'),
('gotverenlerin', 'tr'),
('kaltaga', 'tr'),
('kaltagı', 'tr'),
('kaltagın', 'tr'),
('kaltak', 'tr'),
('kaltaklar', 'tr'),
('kaltaklara', 'tr'),
('kaltaklarda', 'tr'),
('kaltaklardan', 'tr'),
('kaltakları', 'tr'),
('kaltakların', 'tr'),
('kaltakta', 'tr'),
('kaltaktan', 'tr'),
('orospu', 'tr'),
('orospuda', 'tr'),
('orospudan', 'tr'),
('orospular', 'tr'),
('orospulara', 'tr')
on conflict (word) do nothing;

insert into banned_words (word, lang) values
('orospularda', 'tr'),
('orospulardan', 'tr'),
('orospuları', 'tr'),
('orospuların', 'tr'),
('orospunun', 'tr'),
('orospuya', 'tr'),
('orospuyu', 'tr'),
('otuz birci', 'tr'),
('otuz bircide', 'tr'),
('otuz birciden', 'tr'),
('otuz birciler', 'tr'),
('otuz bircilerde', 'tr'),
('otuz bircilerden', 'tr'),
('otuz bircilere', 'tr'),
('otuz bircileri', 'tr'),
('otuz bircilerin', 'tr'),
('otuz bircinin', 'tr'),
('otuz birciye', 'tr'),
('otuz birciyi', 'tr'),
('saksocu', 'tr'),
('saksocuda', 'tr'),
('saksocudan', 'tr'),
('saksocular', 'tr'),
('saksoculara', 'tr'),
('saksocularda', 'tr'),
('saksoculardan', 'tr'),
('saksocuları', 'tr'),
('saksocuların', 'tr'),
('saksocunun', 'tr'),
('saksocuya', 'tr'),
('saksocuyu', 'tr'),
('sıcmak', 'tr'),
('sik', 'tr'),
('sike', 'tr'),
('siker sikmez', 'tr'),
('siki', 'tr'),
('sikilir sikilmez', 'tr'),
('sikin', 'tr'),
('sikler', 'tr'),
('siklerde', 'tr'),
('siklerden', 'tr'),
('siklere', 'tr'),
('sikleri', 'tr'),
('siklerin', 'tr'),
('sikmek', 'tr'),
('sikmemek', 'tr'),
('sikte', 'tr'),
('sikten', 'tr'),
('siktir', 'tr'),
('siktirir siktirmez', 'tr'),
('tasaga', 'tr'),
('tasagı', 'tr'),
('tasagın', 'tr'),
('tasak', 'tr'),
('tasaklar', 'tr'),
('tasaklara', 'tr'),
('tasaklarda', 'tr'),
('tasaklardan', 'tr'),
('tasakları', 'tr'),
('tasakların', 'tr'),
('tasakta', 'tr'),
('tasaktan', 'tr'),
('yaraga', 'tr'),
('yaragı', 'tr'),
('yaragın', 'tr'),
('yarak', 'tr'),
('yaraklar', 'tr'),
('yaraklara', 'tr'),
('yaraklarda', 'tr'),
('yaraklardan', 'tr'),
('yarakları', 'tr'),
('yarakların', 'tr'),
('yarakta', 'tr'),
('yaraktan', 'tr'),
('13.', 'zh'),
('13点', 'zh'),
('三级片', 'zh'),
('下三烂', 'zh'),
('下贱', 'zh'),
('个老子的', 'zh'),
('九游', 'zh'),
('乳交', 'zh'),
('乳头', 'zh'),
('乳房', 'zh'),
('乳波臀浪', 'zh'),
('交配', 'zh'),
('仆街', 'zh'),
('他奶奶', 'zh'),
('他奶奶的', 'zh'),
('他奶娘的', 'zh'),
('他妈', 'zh'),
('他妈ㄉ王八蛋', 'zh'),
('他妈地', 'zh'),
('他妈的', 'zh'),
('他娘', 'zh'),
('他马的', 'zh'),
('你个傻比', 'zh'),
('你他马的', 'zh'),
('你全家', 'zh'),
('你奶奶的', 'zh'),
('你她马的', 'zh'),
('你妈', 'zh'),
('你妈的', 'zh'),
('你娘', 'zh'),
('你娘卡好', 'zh'),
('你娘咧', 'zh'),
('你它妈的', 'zh'),
('你它马的', 'zh'),
('你是鸡', 'zh'),
('你是鸭', 'zh'),
('你马的', 'zh'),
('做爱', 'zh'),
('傻比', 'zh'),
('傻逼', 'zh'),
('册那', 'zh'),
('军妓', 'zh'),
('几八', 'zh'),
('几叭', 'zh'),
('几巴', 'zh'),
('几芭', 'zh'),
('刚度', 'zh'),
('刚瘪三', 'zh'),
('包皮', 'zh'),
('十三点', 'zh'),
('卖b', 'zh'),
('卖比', 'zh'),
('卖淫', 'zh'),
('卵子', 'zh'),
('双峰微颤', 'zh'),
('口交', 'zh'),
('口肯', 'zh'),
('叫床', 'zh'),
('吃屎', 'zh'),
('后庭', 'zh'),
('吹箫', 'zh'),
('塞你公', 'zh'),
('塞你娘', 'zh'),
('塞你母', 'zh'),
('塞你爸', 'zh'),
('塞你老师', 'zh'),
('塞你老母', 'zh'),
('处女', 'zh'),
('外阴', 'zh'),
('大卵子', 'zh'),
('大卵泡', 'zh'),
('大鸡巴', 'zh'),
('奶奶的熊', 'zh'),
('奶子', 'zh'),
('奸你', 'zh'),
('她妈地', 'zh'),
('她妈的', 'zh'),
('她马的', 'zh'),
('妈b', 'zh'),
('妈个b', 'zh'),
('妈个比', 'zh'),
('妈个老比', 'zh'),
('妈妈的', 'zh'),
('妈比', 'zh'),
('妈的', 'zh'),
('妈的b', 'zh'),
('妈逼', 'zh'),
('妓女', 'zh'),
('妓院', 'zh'),
('妳她妈的', 'zh'),
('妳妈的', 'zh'),
('妳娘的', 'zh'),
('妳老母的', 'zh'),
('妳马的', 'zh'),
('姘头', 'zh'),
('姣西', 'zh'),
('娘个比', 'zh'),
('娘的', 'zh'),
('婊子', 'zh'),
('婊子养的', 'zh'),
('嫖娼', 'zh'),
('嫖客', 'zh'),
('它妈地', 'zh'),
('它妈的', 'zh'),
('密洞', 'zh'),
('射你', 'zh'),
('小乳头', 'zh'),
('小卵子', 'zh'),
('小卵泡', 'zh'),
('小瘪三', 'zh'),
('小肉粒', 'zh'),
('小骚比', 'zh'),
('小骚货', 'zh'),
('小鸡巴', 'zh'),
('小鸡鸡', 'zh'),
('屁眼', 'zh'),
('屁股', 'zh'),
('干x娘', 'zh'),
('干七八', 'zh'),
('干你', 'zh'),
('干你妈', 'zh'),
('干你娘', 'zh'),
('干你老母', 'zh'),
('干你良', 'zh'),
('干妳妈', 'zh'),
('干妳娘', 'zh')
on conflict (word) do nothing;

insert into banned_words (word, lang) values
('干妳老母', 'zh'),
('干妳马', 'zh'),
('干您娘', 'zh'),
('干机掰', 'zh'),
('干死cs', 'zh'),
('干死gm', 'zh'),
('干死你', 'zh'),
('干死客服', 'zh'),
('强奸', 'zh'),
('强奸你', 'zh'),
('性器', 'zh'),
('性无能', 'zh'),
('性爱', 'zh'),
('情色', 'zh'),
('想上你', 'zh'),
('懆您妈', 'zh'),
('懆您娘', 'zh'),
('懒8', 'zh'),
('懒八', 'zh'),
('懒叫', 'zh'),
('懒教', 'zh'),
('成人', 'zh'),
('我操你祖宗十八代', 'zh'),
('扒光', 'zh'),
('打炮', 'zh'),
('打飞机', 'zh'),
('抽插', 'zh'),
('招妓', 'zh'),
('插你', 'zh'),
('插死你', 'zh'),
('撒尿', 'zh'),
('操你', 'zh'),
('操你全家', 'zh'),
('操你奶奶', 'zh'),
('操你妈', 'zh'),
('操你娘', 'zh'),
('操你祖宗', 'zh'),
('操你老妈', 'zh'),
('操你老母', 'zh'),
('操妳', 'zh'),
('操妳全家', 'zh'),
('操妳妈', 'zh'),
('操妳娘', 'zh'),
('操妳祖宗', 'zh'),
('操机掰', 'zh'),
('操比', 'zh'),
('操逼', 'zh'),
('放荡', 'zh'),
('日他娘', 'zh'),
('日你', 'zh'),
('日你妈', 'zh'),
('日你老娘', 'zh'),
('日你老母', 'zh'),
('日批', 'zh'),
('月经', 'zh'),
('机八', 'zh'),
('机巴', 'zh'),
('机机歪歪', 'zh'),
('杂种', 'zh'),
('浪叫', 'zh'),
('淫妇', 'zh'),
('淫棍', 'zh'),
('淫水', 'zh'),
('淫秽', 'zh'),
('淫荡', 'zh'),
('淫西', 'zh'),
('湿透的内裤', 'zh'),
('激情', 'zh'),
('灨你娘', 'zh'),
('烂货', 'zh'),
('烂逼', 'zh'),
('狗屁', 'zh'),
('狗日', 'zh'),
('狗狼养的', 'zh'),
('玉杵', 'zh'),
('王八蛋', 'zh'),
('瓜娃子', 'zh'),
('瓜婆娘', 'zh'),
('瓜批', 'zh'),
('瘪三', 'zh'),
('白烂', 'zh'),
('白痴', 'zh'),
('白癡', 'zh'),
('祖宗', 'zh'),
('私服', 'zh'),
('笨蛋', 'zh'),
('精子', 'zh'),
('老二', 'zh'),
('老味', 'zh'),
('老母', 'zh'),
('老瘪三', 'zh'),
('老骚比', 'zh'),
('老骚货', 'zh'),
('肉壁', 'zh'),
('肉棍子', 'zh'),
('肉棒', 'zh'),
('肉缝', 'zh'),
('肛交', 'zh'),
('肥西', 'zh'),
('色情', 'zh'),
('花柳', 'zh'),
('荡妇', 'zh'),
('贝肉', 'zh'),
('贱b', 'zh'),
('贱人', 'zh'),
('贱货', 'zh'),
('贼你妈', 'zh'),
('赛你老母', 'zh'),
('赛妳阿母', 'zh'),
('赣您娘', 'zh'),
('轮奸', 'zh'),
('迷药', 'zh'),
('逼样', 'zh'),
('野鸡', 'zh'),
('阳具', 'zh'),
('阳萎', 'zh'),
('阴唇', 'zh'),
('阴户', 'zh'),
('阴核', 'zh'),
('阴毛', 'zh'),
('阴茎', 'zh'),
('阴道', 'zh'),
('阴部', 'zh'),
('雞巴', 'zh'),
('靠北', 'zh'),
('靠母', 'zh'),
('靠爸', 'zh'),
('靠背', 'zh'),
('靠腰', 'zh'),
('驶你公', 'zh'),
('驶你娘', 'zh'),
('驶你母', 'zh'),
('驶你爸', 'zh'),
('驶你老师', 'zh'),
('驶你老母', 'zh'),
('骚比', 'zh'),
('骚货', 'zh'),
('骚逼', 'zh'),
('鬼公', 'zh'),
('鸡8', 'zh'),
('鸡八', 'zh'),
('鸡叭', 'zh'),
('鸡吧', 'zh'),
('鸡奸', 'zh'),
('鸡巴', 'zh'),
('鸡芭', 'zh'),
('鸡鸡', 'zh'),
('龟儿子', 'zh'),
('龟头', 'zh'),
('陰莖', 'zh'),
('咸家鏟', 'zh'),
('冚家鏟', 'zh'),
('咸家伶', 'zh'),
('冚家拎', 'zh'),
('笨實', 'zh'),
('粉腸', 'zh'),
('屎忽', 'zh'),
('躝癱', 'zh'),
('你老闆', 'zh'),
('你老味', 'zh'),
('你老母', 'zh'),
('硬膠', 'zh')
on conflict (word) do nothing;

create or replace function moderar_mensaje()
returns trigger
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_texto_normalizado text;
  v_palabras_encontradas text[];
  v_palabra text;
  v_count int;
begin
  v_texto_normalizado := lower(unaccent(NEW.text));

  select array_agg(distinct b.word) into v_palabras_encontradas
  from banned_words b
  where position(b.word in v_texto_normalizado) > 0;

  if v_palabras_encontradas is null then
    return NEW;
  end if;

  foreach v_palabra in array v_palabras_encontradas loop
    NEW.text := regexp_replace(NEW.text, v_palabra, repeat('*', length(v_palabra)), 'gi');
  end loop;

  insert into chat_warnings (chat_id, user_id, count)
  values (NEW.chat_id, NEW.sender_id, 1)
  on conflict (chat_id, user_id) do update set count = chat_warnings.count + 1
  returning count into v_count;

  if v_count >= 3 then
    delete from chats where id = NEW.chat_id;
    return null; -- cancela este insert — la sala ya no existe
  end if;

  return NEW;
end;
$$;

drop trigger if exists moderar_mensaje_trigger on messages;
create trigger moderar_mensaje_trigger
  before insert on messages
  for each row
  execute function moderar_mensaje();

-- Salir del chat = se borra para las dos familias (cascada limpia
-- chat_participants y messages). Solo puede salir quien sea participante.
create or replace function leave_chat(p_chat_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1 from chat_participants where chat_id = p_chat_id and user_id = auth.uid()
  ) then
    raise exception 'No sos participante de esta sala';
  end if;
  delete from chats where id = p_chat_id;
end;
$$;

revoke all on function leave_chat(uuid) from public;
grant execute on function leave_chat(uuid) to authenticated;
